#!/bin/bash
# author : lordpax
# backup v2.1
# Petit script de backup

export TEXTDOMAIN="backup"

pass=""
encrypt=0
tmp_folders=""
backup_folders=""
backup_dest="."
log=0
logFile=""
version="v2.1"

#echo_deb <msg>
function echo_log() {
    if [ "A$1" != "A" ] && [ "A$logFile" != "A" ]; then
        local date=$(date "+%Y-%m-%d %H:%M:%S")
        echo -e "$date : $1" >> $logFile
    fi
}

#echo_err <msg>
function echo_err() {
    if [ "A$1" != "A" ]; then
        if [ $log -eq 1 ]; then
            echo_log "ERROR : $1"
        else
            echo -e "\e[31mERROR :\e[0m $1" > /dev/stderr
        fi
    fi
}

#echo_out <msg>
function echo_out() {
    if [ "A$1" != "A" ]; then
        if [ $log -eq 1 ]; then
            echo_log "$1" 
        else
            echo -e "$1"
        fi
    fi
}

function helpFunc() {
    echo_out $"Usage : $0 [option]

Option :
-h or --help ........................... Show help
-v or --version ........................ Show version
-f \"<dir1> [dirN]\" ..................... Source folder
-o <outputDir> ......................... Destination folder
-p <pass> .............................. Pass phrase
-c <config> ............................ File which contain source folders name
-l <logFile> ........................... Log file

Example :
backup -f \"dir_1 dir_2 dir_3\" -o dest_folder
backup -c config.txt -o dest_folder
backup -f \"dir_1 dir_2 dir_3\" -o dest_folder -l logfile.log
backup -f \"dir_1 dir_2 dir_3\" -o dest_folder -p passphrase"

    exit 0
}

function verification() {
    if [ "A$tmp_folders" != "A" ]; then
        for file in $tmp_folders; do
            if [ -d $file ] || [ -f $file ]; then
                backup_folders="$backup_folders $file"
            else
                echo_err $"Source \"$file\" folder does not exist"
            fi
        done
    else
        echo_err $"Source folder is missing"
        exit 1
    fi

    if [ "A$backup_dest" != "A" ]; then
        if [ ! -d $backup_dest ]; then
            echo_err $"Destination \"$backup_dest\" folder does not exist"
            exit 1
        fi
    else
        echo_err $"Destination folder is missing"
        exit 1
    fi

    if [ $encrypt -eq 1 ] && [ "A$pass" = "A" ]; then
        echo_err $"Passphrase is missing"
        exit 1
    fi

    if [ $log -eq 1 ] && [ "A$logFile" = "A" ]; then
        log=0
        echo_err $"Log file is missing"
        exit 1
    fi
}

# readConfig <config>
function readConfig() {
    if [ "A$1" != "A" ]; then
        while read line; do
            tmp_folders="$tmp_folders $line"
        done < $1
    fi
}

function encryptFile() {
    echo_out $"Encryption of $backup_dest/$archive_name"
    if ! gpg --batch --passphrase $pass -c $backup_dest/$archive_name; then
        echo_err $"Something wrong with encrytion"
        exit 1
    fi
    rm $backup_dest/$archive_name
    echo_out $"Encryption $backup_dest/$archive_name.gpg end"
}

function compressFile() {
    local date=$(date +%Y-%m-%d)
    local hostname=$(hostname -s)
    archive_name="backup_${hostname}_${date}.tar.gz"
    local out=$([ $log -eq 1 ] && echo /dev/null || echo /dev/stdout)

    echo_out $"Compress of :"
    for file in $backup_folders; do
        echo_out "  -> $file"
    done
        
    if ! tar czfv $backup_dest/$archive_name $backup_folders &> $out; then
        echo_err $"Something wrong with compression"
        exit 1
    fi
    echo_out $"Backup $backup_dest/$archive_name end"
}

if [ $# -ge 1 ]; then
    for i in $(seq 1 $#); do
        if [ "$1" == "--help" ] || [ "$1" == "-h" ]; then 
            helpFunc
        elif [ "$1" == "--version" ] || [ "$1" == "-v" ]; then 
            echo_out $version
            exit 0
        elif [ "$1" == "-f" ]; then
            shift
            tmp_folders=$1
        elif [ "$1" == "-o" ]; then
            shift
            backup_dest=$1
        elif [ "$1" == "-c" ]; then
            shift
            readConfig $1
        elif [ "$1" == "-l" ]; then
            shift
            log=1
            logFile=$1
        elif [ "$1" == "-p" ]; then
            shift
            encrypt=1
            pass=$1
        fi
        shift
    done
fi

verification
compressFile
[ $encrypt -eq 1 ] && encryptFile