#!/bin/bash

name=$(basename "$0")
repo="https://raw.githubusercontent.com/LordPax/dotfile"
branch="$DOTFILE_BRANCH"
files=""
backup=0
mode=0
output="$HOME"
version="v0.1.2"

# echoErr <msg>
function echoErr() {
    [ -z "$1" ] && exit 1
    echo -e "\e[31mERROR :\e[0m $1" > /dev/stderr
}

function helpFunc() {
    echo "Usage: $name [options] <file> [files] ...

Options :
-h or --help       Display this help
-v or --version    Display version
-b <branch>        Branch to use (default: $branch)
-o <file>          Output directory
-B                 Backup of an existing file and add \"_old\" at the end
-r                 Output file to stdout
-d                 Diff between local and remote file

Example :
$name .vimrc
$name .vimrc .tmux.conf
$name -B .vimrc
$name -o .config i3/config
$name -B -o .config i3/config"
}

function verification() {
    [ -z "$(which bat 2> /dev/null)" ] && echo_err "\"bat\" is required for syntax highligting" && exit 1
    [ -z "$branch" ] && echoErr "No branch specified" && exit 1
    [ -z "$files" ] && echoErr "No files specified" && exit 1
}

# getDotFile <branch> <file>
function getFile() {
    ([ -z "$1" ] || [ -z "$2" ]) && echoErr "Parameter needed for \"getFile\"" && exit 1

    echo "Downloading \"$2\" from \"$1\" branch ..."

    local out=$([ -z "$output" ] && echo "$2" || echo "$output/$2")
    local rename="${out}_old"

    if [ $backup -eq 1 ] && [ -f "$out" ]; then
        mv "$out" "$rename"
        echo "Old file renamed to \"$rename\""
    fi

    if ! wget "$repo/$1/$2" -O "$out" 2> /dev/null; then
        echoErr "Something went wrong while downloading \"$2\""
        if [ $backup -eq 1 ] && [ -f "$rename" ]; then
            mv "$rename" "$out"
            echo "Old file restored"
        fi
        return 1
    fi
}

# readFile <branch> <file>
function readFile() {
    ([ -z "$1" ] || [ -z "$2" ]) && echoErr "Parameter needed for \"readFile\"" && exit 1

    if ! wget "$repo/$1/$2" -O - 2> /dev/null; then
        echoErr "Something went wrong while reading \"$2\""
        return 1
    fi
}

# diffFile <branch> <file>
function diffFile () {
    ([ -z "$1" ] || [ -z "$2" ]) && echoErr "Parameter needed for \"diffFile\"" && exit 1
    local out=$([ -z "$output" ] && echo "$2" || echo "$output/$2")
    [ ! -f "$out" ] && echoErr "File \"$out\" doesn't exist" && exit 1

    diff -u "$out" <(wget "$repo/$1/$2" -O - 2> /dev/null)
    local res=$?

    if [ $res -eq 0 ]; then
        echoErr "No difference between local and remote \"$out\""
    elif [ $res -eq 2 ]; then
        echoErr "Something went wrong while doing diff of \"$out\""
        return 1
    fi
}

if [ $# -ge 1 ]; then
    for i in $(seq 1 $#); do
        case $1 in
            -h | --help)
                helpFunc
                exit 0;;
            -v | --version)
                echo "$version"
                exit 0;;
            -b)
                branch="$2"
                shift;;
            -B)
                backup=1;;
            -r)
                mode=1;;
            -d)
                mode=2;;
            -o)
                output="$2"
                shift;;
            "") ;;
            -*)
                echoErr $"Unknown parameter \"$1\""
                exit 1;;
            *)
                files+=" $1"
        esac
        shift
    done
fi

verification

for file in $files; do
    case $mode in
        0)
            getFile "$branch" "$file";;
        1)
            readFile "$branch" "$file" | bat -p;;
        2)
            diffFile "$branch" "$file" | bat -p;;
    esac
done
